# Generated by Django 5.1.3 on 2024-12-04 17:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Great Game, Good Fun', max_length=255)),
                ('slots', models.DecimalField(decimal_places=0, default=5, max_digits=2)),
                ('description', models.TextField(default='Have fun with me!')),
                ('private', models.BooleanField(default=False)),
                ('buy_in', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('blinds', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('amount_reserved', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('time_start', models.DateTimeField()),
                ('time_created', models.DateField(default=django.utils.timezone.now, null=True)),
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(max_length=1024)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
