# Generated by Django 5.1.3 on 2024-12-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_id',
            new_name='unique_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='amount_reserved',
        ),
        migrations.AlterField(
            model_name='game',
            name='blinds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='buy_in',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='slots',
            field=models.IntegerField(default=5, max_length=2),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
