# Generated by Django 5.1.3 on 2024-12-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_rename_game_id_game_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slots',
            field=models.IntegerField(default=5),
        ),
    ]
