# Generated by Django 5.1.3 on 2024-12-10 22:23

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_start',
            field=models.DateField(default=datetime.date(2024, 12, 10), null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_start',
            field=models.TimeField(default=datetime.time(22, 23, 18, 425569)),
        ),
    ]
