# Generated by Django 5.1.3 on 2024-12-13 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_date_start_alter_game_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_start',
            field=models.DateField(default=datetime.date(2024, 12, 13), null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_start',
            field=models.TimeField(default=datetime.time(19, 0, 37, 243121)),
        ),
    ]
