# Generated by Django 5.1.3 on 2024-12-13 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_game_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 13, 19, 20, 9, 653492, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_start',
            field=models.TimeField(default=datetime.time(19, 20, 9, 653467), null=True),
        ),
    ]
