# Generated by Django 5.1.3 on 2024-12-13 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_game_time_created_alter_game_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 13, 19, 21, 23, 194672, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_start',
            field=models.TimeField(default=datetime.time(19, 21, 23, 194644), null=True),
        ),
    ]
