# Generated by Django 5.1.3 on 2024-11-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='department',
            field=models.CharField(max_length=200),
        ),
    ]
