# Generated by Django 5.1.3 on 2024-11-23 20:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_games', '0002_host_delete_apple'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Host',
            new_name='Game',
        ),
    ]
